### ISSUE TITLE
Hello, I want to ask how to view the frame data of the .aris image file that has been obtained.

### ISSUE THREAD

**Issue by bbbmbbbm** [SoundMetrics/aris-file-sdk#50]
By looking at the information you gave, I think the program to get the frame data in the .aris image file is aris-file-sdk/common-code. If not, please correct it.
By running the program, this problem occurred: error LNK2019: unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ).
By searching for information, I would like to ask whether this project is a windows program or a DOS console program?
Hope to get your reply and help, thank you very much!

**Comment by curtnichols** [comment]
Customer program needs its own `main` method.
